config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :genres
  resources :movies

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.order(:title)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    @genres = Genre.all
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    @genres = params[:movie][:genre_ids]

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :poster, :wallpaper, :running_time, :director, genre_ids:[])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def test
    #Assign genre to movie
    #@genre = Genre.find_by(name: 'Science Fiction')
    #@movie = Movie.first
    #@movie.genres << @genre

    render json: @movie = Movie.first.genres
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-6 medium-6 small-12 columns">
      <label>
        <h2 class="label-text">Name</h2>
          <%= f.text_field :name %>
      </label>
     </div>
    <div class="large-12 columns">
      <label>
        <h2 class="label-text">Description</h2>
        <%= f.text_area :description, {:rows => '10'} %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-4 columns">
      <%= f.submit 'Submit', {:class => 'button secondary large'} %>
    </div>
  </div>
<% end %>
</div>
</div><!-- end container -->

<div class="row row-buffer"></div>

<div class="row">
  <div class="large-12 colums">
    <ul class="menu">
      <li>
        <%= link_to 'Back', genres_path %>
      </li>
    </ul>
  </div>
</div>

app/views/genres/edit.html.erb
<div class="row row-buffer"></div>

<div class="row container">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <h1 class="white">Edit Genre</h1>
      </div>
    </div>

    <%= render 'form' %>

app/views/genres/index.html.erb
<div id="bar">
  <div class="row">
    <div class="large-16 column">
      <div class="menu-centered">
        <ul class="menu">
          <li class="inactive">
            <%= link_to 'HOME', root_path %>
          </li>
          <li class="inactive">
            <%= link_to 'MOVIES', movies_path %>
          </li>
          <li class="active">
            <%= link_to 'GENRES', genres_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row container">

  <div class="large-12 columns">

    <% if !notice.nil? %>
        <div class="row row-buffer"></div>

        <div class="row">
          <div class="large-6 medium-6 small-6 columns">
            <div class="callout primary">
              <%= notice %>
            </div>
          </div>
        </div>
  <% end %>

    <div class="row row-buffer"></div>
  </div>

  <div class="large-6 medium-6 small-6 columns">
    <div class="callout primary">
      Click on a genre to view more details!
    </div>
  </div>
  <div class="large-12 columns">
    <canvas class="full-width" id="canvas" height="500" width="1200"></canvas>
  </div>

  <div class="row row-buffer"></div>

</div><!-- end container -->

<div class="row row-buffer"></div>

<div class="row">
  <div class="large-12 colums">
    <ul class="menu">
      <li>
        <%= link_to 'NEW GENRE', new_genre_path %>
      </li>
    </ul>
  </div>
</div>

<script>

  var w = $('div.row').width();
  $('#canvas').width(w * 0.97);

  var elements = [
    <%@genres.each do |genre| %>
      ['<%= genre.name %>', <%= 50 + Random.rand(50) %>, <%= genre.id %>],
    <% end %>
  ];
  WordCloud($('#canvas')[0], { list: elements, fontWeight: 'bold', gridSize: 10, backgroundColor: 'white',
    rotateRatio: 0.5, shuffle: true, wait: 80, click: function(item, dimension, event) {
        window.location += '/' + item[2];
    }
  });
</script>

app/views/genres/new.html.erb
<div class="row row-buffer"></div>

<div class="row container">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <h1 class="white">New Genre</h1>
      </div>
    </div>
    <%= render 'form' %>

app/views/genres/show.html.erb
<div id="bar">
  <div class="row">
    <div class="large-16 column">
      <div class="menu-centered">
        <ul class="menu">
          <li class="inactive">
            <%= link_to 'HOME', root_path %>
          </li>
          <li class="inactive">
            <%= link_to 'MOVIES', movies_path %>
          </li>
          <li class="inactive">
            <%= link_to 'GENRES', genres_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row container">
  <div class="large-12 columns">

    <% if !notice.nil? %>
        <div class="row row-buffer"></div>

        <div class="row">
          <div class="large-6 medium-6 small-6 columns">
            <div class="callout primary">
              <%= notice %>
            </div>
          </div>
        </div>
    <% end %>

    <div class="row row-buffer"></div>

    <div class="row">
      <div class="large-12 columns">
        <div class="wallpaper-column">
          <img class="wallpaper" src="../images/genreWallpaper.jpg">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <h1 class="title"><%= @genre.name %></h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 medium-12 small-12 columns genre-info">
        <h4 class="info-key noselect">Description:</h4>
        <p class="info-value">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
      </div>
    </div>

    <div class="row row-buffer"></div>

    <div class="row">
      <div class="large-12 columns">
        <h4 class="white noselect">Movies with the same genre:</h4>
      </div>
    </div>

    <div class="row">
      <% @genre.movies.each do |movie| %>
      <div class="large-3 columns end">
        <%= link_to movie do %>
            <img class="movie-poster" src="../images/<%= movie.poster %>">
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="row row-buffer"></div>

  </div>
</div><!-- end container -->

<div class="row row-buffer"></div>

<div class="row">
  <div class="large-12 colums">
    <ul class="menu">
      <li>
        <%= link_to 'BACK', genres_path, {:class => 'back'} %>
      </li>
      <li>
        <%= link_to 'EDIT GENRE', edit_genre_path(@genre), {:class => 'edit'} %>
      </li>
      <li>
        <%= link_to 'DELETE GENRE', @genre, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>
  </div>
</div>

<div class="row row-buffer"></div>

<script>
      $(document).foundation();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
    <% if @movie.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

          <ul>
            <% @movie.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <div class="row">
        <div class="large-6 medium-6 small-12 columns">
          <label>
            <h2 class="label-text">Title</h2>
            <%= f.text_field :title %>
          </label>
        </div>
        <div class="large-3 medium-3 small-6 columns">
          <label>
            <h2 class="label-text">Director</h2>
            <%= f.text_field :director %>
          </label>
        </div>
        <div class="large-3 medium-3 small-6 columns">
          <div class="row">
            <div class="large-12 columns">
              <label>
                <h2 class="label-text">Duration</h2>
              </label>
            </div>
            <div class="large-12 columns">
              <div class="input-group">
                <%= f.number_field :running_time, { :class => 'input-group-field text-center'} %>
                <span class="input-group-label">Minutes</span>
              </div>
            </div>
          </div>
        </div>
        <div class="large-12 columns">
          <label>
            <h2 class="label-text">Select Genre</h2>
            <fieldset class="large-12 columns">
              <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
            </fieldset>
          </label>
        </div>
        <div class="large-12 columns">
          <label>
            <h2 class="label-text">Description</h2>
            <%= f.text_area :description, {:rows => '10'} %>
          </label>
        </div>
        <div class="large-6 medium-6 small-12 columns">
          <label>
            <h2 class="label-text">Cover File Name</h2>
            <%= f.text_field :poster %>
          </label>
        </div>
        <div class="large-6 medium-6 small-12 columns">
          <label>
            <h2 class="label-text">Wallpaper File Name</h2>
            <%= f.text_field :wallpaper %>
          </label>
        </div>
      </div>
      <div class="row">
        <div class="large-4 columns">
          <%= f.submit 'Submit', {:class => 'button secondary large'} %>
        </div>
      </div>
<% end %>
</div>
</div><!-- end container -->


<div class="row row-buffer"></div>

<div class="row">
  <div class="large-12 colums">
    <ul class="menu">
      <li>
        <%= link_to 'Back', movies_path %>
      </li>
    </ul>
  </div>
</div>

app/views/movies/edit.html.erb
<div class="row row-buffer"></div>

<div class="row container">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <h1 class="white">Edit Movie</h1>
      </div>
    </div>

    <%= render 'form' %>

app/views/movies/index.html.erb
<div id="bar">
  <div class="row">
    <div class="large-16 column">
      <div class="menu-centered">
        <ul class="menu">
          <li class="inactive">
            <%= link_to 'HOME', root_path %>
          </li>
          <li class="active">
            <%= link_to 'MOVIES', movies_path %>
          </li>
          <li class="inactive">
            <%= link_to 'GENRES', genres_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row container">
  <div class="large-12 columns">

    <% if !notice.nil? %>
        <div class="row row-buffer"></div>

        <div class="row">
          <div class="large-6 medium-6 small-6 columns">
            <div class="callout primary">
              <%= notice %>
            </div>
          </div>
        </div>
    <% end %>

    <div class="row row-buffer"></div>

    <div class="row">
      <% @movies.each do |movie| %>
          <div class="large-3 medium-4 columns end">
            <%= link_to movie do %>
              <img class="movie-poster" src="images/<%= movie.poster %>">
            <% end %>
          </div>
    <% end %>
    </div>

  </div>

  <div class="row row-buffer"></div>

</div>

<div class="row row-buffer"></div>

<div class="row">
  <div class="large-12 colums">
    <ul class="menu">
      <li>
        <%= link_to 'NEW MOVIE', new_movie_path %>
      </li>
    </ul>
  </div>
</div>

app/views/movies/new.html.erb
<div class="row row-buffer"></div>

<div class="row container">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <h1 class="white">New Movie</h1>
      </div>
    </div>
    <%= render 'form' %>

app/views/movies/show.html.erb
<div id="bar">
  <div class="row">
    <div class="large-16 column">
      <div class="menu-centered">
        <ul class="menu">
          <li class="inactive">
            <%= link_to 'HOME', root_path %>
          </li>
          <li class="inactive">
            <%= link_to 'MOVIES', movies_path %>
          </li>
          <li class="inactive">
            <%= link_to 'GENRES', genres_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row container">
  <div class="large-12 columns">

    <% if !notice.nil? %>
        <div class="row row-buffer"></div>

        <div class="row">
          <div class="large-6 medium-6 small-6 columns">
            <div class="callout primary">
              <%= notice %>
            </div>
          </div>
        </div>
    <% end %>

    <div class="row row-buffer"></div>

    <div class="row">
      <div class="large-12 columns">
        <div class="wallpaper-column">
          <img class="wallpaper" src="../images/<%= @movie.wallpaper %>">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="show-for-medium-only">
        <div class="medium-4 medium-offset-8 columns cover-column-medium">
          <img class="cover" src="../images/<%= @movie.poster %>">
        </div>
      </div>
      <div class="hide-for-medium-only hide-for-small-only">
        <div class="large-4 large-offset-8 columns cover-column-large">
          <img class="cover" src="../images/<%= @movie.poster %>">
        </div>
      </div>
    </div>

    <div class="row movie-info">
      <div class="large-8 columns">
        <div class="row">
          <div class="large-12 columns">
            <h1 class="title"><%= @movie.title %></h1>
          </div>

          <div class="large-12 columns">
            <div class="row">
              <div class="large-4 medium-4 small-4 columns">
                <h4 class="info-key genre noselect">Running Time:</h4>
                <p class="info-value"><%= @movie.running_time %> min</p>
              </div>
              <div class="large-4 medium-4 small-4 columns movie-info-col">
                <h4 class="info-key genre noselect">Director:</h4>
                <p class="info-value"><%= @movie.director %></p>
              </div>
              <div class="large-4 medium-4 small-4 columns movie-info-col">
                <h4 class="info-key genre noselect">Rating:</h4>
                <p class="info-value">
                  <i class="fi-star"></i>
                  <i class="fi-star"></i>
                  <i class="fi-star"></i>
                  <i class="fi-star"></i>
                  <i class="fi-star empty-star"></i>
                </p>
              </div>
            </div>
          </div>
          <div class="large-12 columns">
            <h3 class="info-key genre">Genres:</h3>
            <p class="info-value">
              <% @movie.genres.each do |genre| %>
              <%= link_to genre.name, genre_path(genre) %>,
              <% end %>
            </p>
          </div>
        </div>
      </div>
      <div class="large-12 columns">
        <h3 class="info-key genre">Description:</h3>
        <p class="description info-value"><%= @movie.description %></p>
      </div>
    </div>

    <div class="row row-buffer"></div>

  </div>
</div><!-- end container -->

<div class="row row-buffer"></div>

<div class="row">
  <div class="large-12 colums">
    <ul class="menu">
      <li>
        <%= link_to 'BACK', movies_path, { :class => 'back'} %>
      </li>
      <li>
        <%= link_to 'EDIT MOVIE', edit_movie_path(@movie), { :class => 'edit'} %>
      </li>
      <li>
        <%= link_to 'DELETE MOVIE', @movie, method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>
  </div>
</div>

<div class="row row-buffer"></div>

app/views/welcome/index.html.erb
<div id="banner">
  <p class="title">Movie Library</p>
</div>

<div id="bar">
  <div class="row">
    <div class="large-16 column">
      <div class="menu-centered">
        <ul class="menu">
          <li class="active">
            <%= link_to 'HOME', root_path %>
          </li>
          <li class="inactive">
            <%= link_to 'MOVIES', movies_path %>
          </li>
          <li class="inactive">
            <%= link_to 'GENRES', genres_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-8 columns">

  </div>
</div>